---
root: true

parserOptions:
  ecmaVersion: latest
  sourceType: module

env:
  node: true
  browser: false
  es6: true

rules:
  node/handle-callback-err: off
  node/no-callback-literal: off

  comma-dangle:
    - error
    - only-multiline
  indent: off
  multiline-ternary: off
  no-case-declarations: off
  no-fallthrough: off
  no-return-await: off
  no-template-curly-in-string: off
  no-useless-escape: off
  prefer-promise-reject-errors: off
  prefer-optional-chain: off
  semi: off
  space-before-function-paren: off
  spaced-comment: off
  symbol-description: off
